clc;clear all ;close all;
a=inputdlg({'m1 :','m2 :','radius :','L :'},'inputs',1,{'1','1','1','1'});
m1=str2double(a{1});
m2=str2double(a{2});
R=str2double(a{3});
L=str2double(a{4});
alpha=acos(L/(2*R));
l=(m1*L)/(m1+m2);
oc=sqrt(l^2+R^2-2*R*l*cos(alpha));
phi=asin((l*sin(alpha))/oc);
gamma=pi-2*alpha-phi;
miu=0.01;
g=9.81;
% syms gamma miu m1 m2 g theta phi Tdot T2dot oc R 
% A=[cos(gamma)-miu*sin(gamma),cos(phi)+miu*sin(phi);...
%     miu*cos(gamma)+sin(gamma),miu*cos(phi)-sin(phi)];
% B=[Fn+(m1+m2)*g*sin(theta+phi);(m1+m2)*g*cos(theta+phi)-Ft];
% X=A\B;
% N1=-(Ft*cos(phi) - Fn*sin(phi) - g*m1*cos(theta) - g*m2*cos(theta) +...
%     Fn*miu*cos(phi) + Ft*miu*sin(phi) + g*m1*miu*sin(theta) +...
%     g*m2*miu*sin(theta))/(sin(gamma + phi)*miu^2 + sin(gamma + phi));
% N2=(Ft*cos(gamma) + Fn*sin(gamma) - g*m1*cos(gamma + phi + theta) - ...
%     g*m2*cos(gamma + phi + theta) + Fn*miu*cos(gamma) - Ft*miu*sin(gamma)...
%     + g*m1*miu*sin(gamma + phi + theta) + ...
%     g*m2*miu*sin(gamma + phi + theta))/(sin(gamma + phi)*miu^2 + ...
%     sin(gamma + phi));
% Ft=(m1+m2)*g*cos(theta+phi)-miu*N1*cos(gamma)-miu*N2*cos(phi)-N1*sin(gamma)+N2*sin(phi);
% Fn=-(m1+m2)*g*sin(theta+phi)+N1*cos(gamma)+N2*cos(phi)-miu*N1*sin(gamma)+miu*N2*sin(phi);
% X=m1*g*R*cos(phi+gamma+theta)+m2*g*R*cos(theta)-miu*R*(N1+N2)-Ft*(R^2)/oc;
% (R*(g*m2*oc*cos(theta) - Ft*R*miu^2 - Ft*R + g*m1*oc*cos(gamma + phi + theta)...
%     + g*m2*miu^2*oc*cos(theta) + g*m1*miu^2*oc*cos(gamma + phi + theta)))/(oc*(miu^2 + 1))...
%     - (R*(Ft*miu*oc*cos(gamma) - Ft*miu*oc*cos(phi) + Fn*miu*oc*sin(gamma) + Fn*miu*oc*sin(phi)...
%     + Fn*miu^2*oc*cos(gamma) - Fn*miu^2*oc*cos(phi) - Ft*miu^2*oc*sin(gamma) - Ft*miu^2*oc*sin(phi)...
%     - g*m1*miu*oc*cos(gamma + phi + theta) - g*m2*miu*oc*cos(gamma + phi + theta) - g*m1*miu^2*oc*sin(theta)...
%     - g*m2*miu^2*oc*sin(theta) + g*m1*miu^2*oc*sin(gamma + phi + theta) + g*m2*miu^2*oc*sin(gamma + phi + theta)...
%     + g*m1*miu*oc*cos(theta) + g*m2*miu*oc*cos(theta)))/(oc*sin(gamma + phi)*(miu^2 + 1));
% Ft=(m1+m2)*oc*T2dot;
% Fn=(m1+m2)*oc*(Tdot^2);
% Tdot=sqrt(-miu*oc*(miu*sin(phi)*m2-miu*sin(gamma)*m2+miu*sin(phi)*m1-miu*sin(gamma)*m1+cos(gamma)*m1+cos(phi)*m1+cos(gamma)*m2+cos(phi)*m2)*(R*T2dot*m1*miu^2+R*T2dot*m2*miu^2+R*T2dot*m2+R*T2dot*m1+m2*miu*oc*T2dot*sin(phi)+m1*miu*oc*T2dot*sin(phi)-T2dot*miu^2*oc*m1*cos(phi)-T2dot*miu^2*oc*m2*cos(phi)+2*cos(gamma)*cos(theta)*cos(phi)*g*m1*miu^2*sin(gamma)*sin(phi)+g*m1*miu*sin(theta)+g*m2*miu*sin(theta)-g*m2*cos(theta)-g*m1*cos(theta)-R*m2*miu^2*T2dot*sin(gamma)*sin(phi)-R*m1*miu^2*T2dot*sin(gamma)*sin(phi)+R*T2dot*m1*miu^2*cos(phi)*cos(gamma)+R*T2dot*m2*miu^2*cos(phi)*cos(gamma)-m2*miu*oc*T2dot*sin(gamma)-m1*miu*oc*T2dot*sin(gamma)-T2dot*miu^2*oc*m1*cos(gamma)-T2dot*miu^2*oc*m2*cos(gamma)-R*m2*T2dot*sin(gamma)*sin(phi)-R*m1*T2dot*sin(gamma)*sin(phi)+R*T2dot*m2*cos(phi)*cos(gamma)+R*T2dot*m1*cos(phi)*cos(gamma)+2*cos(gamma)*cos(theta)*cos(phi)*g*m1*sin(gamma)*sin(phi)-2*cos(phi)*g*m1*miu^2*sin(theta)*sin(gamma)^2*sin(phi)-2*cos(gamma)*g*m1*miu^2*sin(theta)*sin(gamma)*sin(phi)^2+cos(phi)*g*m1*sin(theta)*sin(phi)+cos(theta)*g*m1*miu^2*sin(phi)^2+cos(gamma)*g*m1*sin(theta)*sin(gamma)+cos(theta)*g*m1*miu^2*sin(gamma)^2-g*m1*cos(theta)*cos(phi)*cos(gamma)-g*m2*cos(theta)*cos(phi)*cos(gamma)+g*m1*sin(theta)*cos(phi)*sin(gamma)+g*m1*sin(theta)*sin(phi)*cos(gamma)+g*m1*cos(theta)*sin(phi)*sin(gamma)+g*m2*cos(theta)*sin(phi)*sin(gamma)-2*cos(theta)*g*m1*sin(gamma)^2*sin(phi)^2+cos(theta)*g*m1*sin(phi)^2+cos(theta)*g*m1*sin(gamma)^2+cos(phi)*g*m1*miu^2*sin(theta)*sin(phi)+cos(gamma)*g*m1*miu^2*sin(theta)*sin(gamma)-g*m2*miu*sin(theta)*sin(gamma)*sin(phi)-g*m1*miu*sin(theta)*sin(gamma)*sin(phi)+g*m1*miu*sin(theta)*cos(phi)*cos(gamma)+g*m2*miu*sin(theta)*cos(phi)*cos(gamma)+cos(theta)*cos(phi)*g*m2*miu*sin(gamma)+cos(theta)*cos(phi)*g*m1*miu*sin(gamma)+cos(gamma)*cos(theta)*g*m2*miu*sin(phi)+cos(gamma)*cos(theta)*g*m1*miu*sin(phi)-cos(phi)*g*m2*miu^2*sin(theta)*sin(gamma)-2*cos(phi)*g*m1*sin(theta)*sin(gamma)^2*sin(phi)-cos(gamma)*g*m2*miu^2*sin(theta)*sin(phi)-2*cos(gamma)*g*m1*sin(theta)*sin(gamma)*sin(phi)^2-2*cos(theta)*g*m1*miu^2*sin(gamma)^2*sin(phi)^2))/(miu*oc*(miu*sin(phi)*m2-miu*sin(gamma)*m2+miu*sin(phi)*m1-miu*sin(gamma)*m1+cos(gamma)*m1+cos(phi)*m1+cos(gamma)*m2+cos(phi)*m2)), -sqrt(-miu*oc*(miu*sin(phi)*m2-miu*sin(gamma)*m2+miu*sin(phi)*m1-miu*sin(gamma)*m1+cos(gamma)*m1+cos(phi)*m1+cos(gamma)*m2+cos(phi)*m2)*(R*T2dot*m1*miu^2+R*T2dot*m2*miu^2+R*T2dot*m2+R*T2dot*m1+m2*miu*oc*T2dot*sin(phi)+m1*miu*oc*T2dot*sin(phi)-T2dot*miu^2*oc*m1*cos(phi)-T2dot*miu^2*oc*m2*cos(phi)+2*cos(gamma)*cos(theta)*cos(phi)*g*m1*miu^2*sin(gamma)*sin(phi)+g*m1*miu*sin(theta)+g*m2*miu*sin(theta)-g*m2*cos(theta)-g*m1*cos(theta)-R*m2*miu^2*T2dot*sin(gamma)*sin(phi)-R*m1*miu^2*T2dot*sin(gamma)*sin(phi)+R*T2dot*m1*miu^2*cos(phi)*cos(gamma)+R*T2dot*m2*miu^2*cos(phi)*cos(gamma)-m2*miu*oc*T2dot*sin(gamma)-m1*miu*oc*T2dot*sin(gamma)-T2dot*miu^2*oc*m1*cos(gamma)-T2dot*miu^2*oc*m2*cos(gamma)-R*m2*T2dot*sin(gamma)*sin(phi)-R*m1*T2dot*sin(gamma)*sin(phi)+R*T2dot*m2*cos(phi)*cos(gamma)+R*T2dot*m1*cos(phi)*cos(gamma)+2*cos(gamma)*cos(theta)*cos(phi)*g*m1*sin(gamma)*sin(phi)-2*cos(phi)*g*m1*miu^2*sin(theta)*sin(gamma)^2*sin(phi)-2*cos(gamma)*g*m1*miu^2*sin(theta)*sin(gamma)*sin(phi)^2+cos(phi)*g*m1*sin(theta)*sin(phi)+cos(theta)*g*m1*miu^2*sin(phi)^2+cos(gamma)*g*m1*sin(theta)*sin(gamma)+cos(theta)*g*m1*miu^2*sin(gamma)^2-g*m1*cos(theta)*cos(phi)*cos(gamma)-g*m2*cos(theta)*cos(phi)*cos(gamma)+g*m1*sin(theta)*cos(phi)*sin(gamma)+g*m1*sin(theta)*sin(phi)*cos(gamma)+g*m1*cos(theta)*sin(phi)*sin(gamma)+g*m2*cos(theta)*sin(phi)*sin(gamma)-2*cos(theta)*g*m1*sin(gamma)^2*sin(phi)^2+cos(theta)*g*m1*sin(phi)^2+cos(theta)*g*m1*sin(gamma)^2+cos(phi)*g*m1*miu^2*sin(theta)*sin(phi)+cos(gamma)*g*m1*miu^2*sin(theta)*sin(gamma)-g*m2*miu*sin(theta)*sin(gamma)*sin(phi)-g*m1*miu*sin(theta)*sin(gamma)*sin(phi)+g*m1*miu*sin(theta)*cos(phi)*cos(gamma)+g*m2*miu*sin(theta)*cos(phi)*cos(gamma)+cos(theta)*cos(phi)*g*m2*miu*sin(gamma)+cos(theta)*cos(phi)*g*m1*miu*sin(gamma)+cos(gamma)*cos(theta)*g*m2*miu*sin(phi)+cos(gamma)*cos(theta)*g*m1*miu*sin(phi)-cos(phi)*g*m2*miu^2*sin(theta)*sin(gamma)-2*cos(phi)*g*m1*sin(theta)*sin(gamma)^2*sin(phi)-cos(gamma)*g*m2*miu^2*sin(theta)*sin(phi)-2*cos(gamma)*g*m1*sin(theta)*sin(gamma)*sin(phi)^2-2*cos(theta)*g*m1*miu^2*sin(gamma)^2*sin(phi)^2))/(miu*oc*(miu*sin(phi)*m2-miu*sin(gamma)*m2+miu*sin(phi)*m1-miu*sin(gamma)*m1+cos(gamma)*m1+cos(phi)*m1+cos(gamma)*m2+cos(phi)*m2));
% T2dot=-(-sin(gamma+phi)*g*m2*miu^2*cos(theta)-sin(gamma+phi)*g*m1*miu^2*cos(gamma+phi+theta)-sin(gamma+phi)*g*m2*cos(theta)-sin(gamma+phi)*g*m1*cos(gamma+phi+theta)-g*m1*miu*cos(gamma+phi+theta)-g*m2*miu*cos(gamma+phi+theta)-g*m1*miu^2*sin(theta)-g*m2*miu^2*sin(theta)+g*m1*miu^2*sin(gamma+phi+theta)+g*m2*miu^2*sin(gamma+phi+theta)+g*m1*miu*cos(theta)+g*m2*miu*cos(theta)+Tdot^2*miu^2*oc*cos(gamma)*m1+Tdot^2*miu^2*oc*cos(gamma)*m2+miu*Tdot^2*oc*sin(phi)*m1+miu*Tdot^2*oc*sin(phi)*m2-Tdot^2*miu^2*oc*cos(phi)*m1-Tdot^2*miu^2*oc*cos(phi)*m2+miu*Tdot^2*oc*sin(gamma)*m1+miu*Tdot^2*oc*sin(gamma)*m2)/(R*sin(gamma+phi)*m2+R*sin(gamma+phi)*m1-miu^2*oc*sin(gamma)*m1-miu^2*oc*sin(gamma)*m2-miu*oc*m1*cos(phi)-miu*oc*m2*cos(phi)-miu^2*oc*sin(phi)*m1-miu^2*oc*sin(phi)*m2+miu*oc*m2*cos(gamma)+R*sin(gamma+phi)*m1*miu^2+R*sin(gamma+phi)*m2*miu^2+miu*oc*m1*cos(gamma));
[T Y]=ode45(@sol,0:0.01:10,[0 0]);

